---

- file: >
    dest={{jenkins_home}}/.ssh
    state=directory
    owner={{jenkins_process_user}}
    group={{jenkins_process_group}}
    mode=0700

- name: jenkins-ssh from file| Copy private key
  copy: >
    src={{jenkins_ssh_key_file}}
    dest={{jenkins_home}}/.ssh/id_rsa
    owner={{jenkins_process_user}}
    group={{jenkins_process_group}}
    mode=0600
  when: jenkins_ssh_key_file != ""

- debug: var=keys

#- name: jenkins-ssh from variable| Copy private key
#  template: >
#    src=ssh_private_key.j2
#    dest="{{jenkins_home}}/.ssh/{{ item.file_name | default('id_rsa') }}"
#    owner={{jenkins_process_user}}
#    group={{jenkins_process_group}}
#    mode=0600
#  with_items: "{{jenkins_ssh_keys}}"
#
- name: jenkins-ssh | Setup SSH hosts
  lineinfile:
    line="{{item}}"
    insertafter="EOF"
    state="present"
    create="yes"
    mode="0644"
    dest="{{jenkins_home}}/.ssh/known_hosts"
    owner="{{jenkins_process_user}}"
  with_items: "{{jenkins_ssh_fingerprints}}"
