---
#- name: Wait for Jenkins to start up before proceeding.
#  shell: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
#  register: result
#  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
#  retries: "{{ jenkins_connection_retries }}"
#  delay: "{{ jenkins_connection_delay }}"
#  changed_when: false
#  check_mode: no

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080/login?from=%2F
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200