spring.data.rest.base-path: /api
server:
    port: 8888
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: true
    hibernate.ddl-auto: create-drop
    hibernate.generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings.web-allow-others: true
xonix:
  default:
    match.duration: 400
    field.height: 30
    field.width:  60
    field.filled: 95
    log.video.dir: ./video
    log.mvn.dir: ./mvn-logs
    log.repositories.dir: ./repositories
    build:
      temp.dir: /tmp
      git.command: git
      mvn.command: mvn
      ffmpeg.command: ffmpeg
applog: /var/log/thumbtack-xonix-mind/service.log
