jenkins_directory: /data/jenkins

directories:
  - '{{ jenkins_directory }}/plugins'
  - '{{ jenkins_directory }}/slaves/cd'
  - /data/.ivy2

jobs:
  - books-service

# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
jenkins_version: "2.107.3"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins:
- name: credentials-binding
  version: 1.16
- name: cloudbees-bitbucket-branch-source
  version: 2.2.11
- name: matrix-project
  version: 1.13
- name: groovy
  version: 2.0
- name: docker-workflow
  version: 1.17
- name: multiple-scms
  version: 0.6
- name: blueocean-rest
  version: 1.5.0
- name: github-branch-source
  version: 2.3.4
- name: branch-api
  version: 2.0.20
- name: structs
  version: 1.14
- name: pipeline-model-api
  version: 1.2.9
- name: command-launcher
  version: 1.2
- name: pipeline-build-step
  version: 2.7
- name: workflow-durable-task-step
  version: 2.19
- name: workflow-cps
  version: 2.53
- name: mailer
  version: 1.21
- name: jenkins-design-language
  version: 1.5.0
- name: bitbucket-build-status-notifier
  version: 1.3.3
- name: jquery-detached
  version: 1.2.1
- name: bitbucket
  version: 1.1.8
- name: script-security
  version: 1.44
- name: authentication-tokens
  version: 1.3
- name: scm-api
  version: 2.2.7
- name: blueocean-core-js
  version: 1.5.0
- name: display-url-api
  version: 2.2.0
- name: config-file-provider
  version: 2.18
- name: git-server
  version: 1.7
- name: pipeline-stage-tags-metadata
  version: 1.2.9
- name: mercurial
  version: 2.3
- name: pipeline-model-extensions
  version: 1.2.9
- name: handy-uri-templates-2-api
  version: 2.1.6-1.0
- name: git
  version: 3.9.0
- name: groovy-postbuild
  version: 2.4.1
- name: workflow-support
  version: 2.18
- name: blueocean-bitbucket-pipeline
  version: 1.5.0
- name: workflow-cps-global-lib
  version: 2.9
- name: jsch
  version: 0.1.54.2
- name: github
  version: 1.29.0
- name: docker-commons
  version: 1.13
- name: blueocean-rest-impl
  version: 1.5.0
- name: job-dsl
  version: 1.69
- name: pipeline-graph-analysis
  version: 1.6
- name: workflow-job
  version: 2.21
- name: ace-editor
  version: 1.1
- name: ssh-credentials
  version: 1.13
- name: pipeline-input-step
  version: 2.8
- name: stashNotifier
  version: 1.13
- name: junit
  version: 1.24
- name: pubsub-light
  version: 1.12
- name: pipeline-multibranch-defaults
  version: 1.1
- name: apache-httpcomponents-client-4-api
  version: 4.5.5-2.1
- name: blueocean-pipeline-scm-api
  version: 1.5.0
- name: blueocean-commons
  version: 1.5.0
- name: plain-credentials
  version: 1.4
- name: workflow-scm-step
  version: 2.6
- name: pipeline-stage-step
  version: 2.3
- name: credentials
  version: 2.1.16
- name: pipeline-model-declarative-agent
  version: 1.1.1
- name: workflow-multibranch
  version: 2.19
- name: blueocean-web
  version: 1.5.0
- name: favorite
  version: 2.3.2
- name: blueocean-jwt
  version: 1.5.0
- name: workflow-api
  version: 2.27
- name: bouncycastle-api
  version: 2.16.2
- name: workflow-step-api
  version: 2.15
- name: pipeline-model-definition
  version: 1.2.9
- name: token-macro
  version: 2.5
- name: variant
  version: 1.1
- name: workflow-basic-steps
  version: 2.7
- name: cloudbees-folder
  version: 6.4
- name: htmlpublisher
  version: 1.16
- name: blueocean-pipeline-api-impl
  version: 1.5.0
- name: git-client
  version: 2.7.2
- name: durable-task
  version: 1.22
- name: badge
  version: 1.4
- name: jackson2-api
  version: 2.8.11.2


jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""
jenkins_admin_token: ""
jenkins_admin_token_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"

#jenkins_admin_token: "{{ lookup('file', '/var/lib/jenkins/secrets/initialAdminPassword') }}"

jenkins_ssh_key_file: "/home/ev/.ssh/id_rsa_jenkins_github"

jenkins_ssh_fingerprints:                   # Set known hosts for ssh
  - "bitbucket.org,131.103.20.167 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=="
  - "github.com,204.232.175.90 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
