Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.box_check_update = false
  config.vm.provider :lxc do |lxc|
     lxc.customize 'cgroup.devices.allow', 'c 10:200 rwm'
     lxc.customize 'apparmor.profile', 'unconfined'
     lxc.customize 'mount.auto', 'cgroup'
#    lxc.customize 'network.ipv4', '10.0.3.15/24' # if LXC 2.0 is installed on host
     lxc.customize 'net.0.ipv4.address', '10.0.3.16/24' # if LXC 3.0 is installed on host
  end
end
